version: '3.3'

networks:
  default:
    driver: bridge

services:
  api: 
    build: ./
    networks: 
      - default
    ports: 
      - "3001:3001"
    environment: 
      PORT: 3001
      DATABASE_URL: "mongodb://localhost:27017/argentBankDB"
    volumes:
      - type: "bind"
        source: "./"
        target: "/app"
    depends_on:
      - mongo
    command: "npm run dev:server"

  mongo:
    image: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    expose:
      - "27017"
  # frontend:
  #   build: ../frontend
  #   restart: always
  #   networks:
  #     - default
  #   ports:
  #     - "3000:3000"
    

  